### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by courteouselk** [pretenders/pretenders#136]
Please see the subject.  What is the license this repo is distributed with?

**Comment by EdlanPolicarpio** [comment]
Going to necro this discussion incase anyone else was also looking for an answer. 
According to https://pypi.org/project/pretenders/ pretenders has an LGPL liscense, I cant find any other licensing information about this repo.

**Comment by txels** [comment]
MIT license has now been explicitly included in the repository.
