### ISSUE TITLE
Is this project being supported anymore?

### ISSUE THREAD

**Issue by conradogarciaberrotaran** [pretenders/pretenders#143]
Hi! We heavily rely on pretenders in several projects. I want to know if this is going to be maintained, If I need to migrate and if so, which new library do you recommend?

Thanks!

**Comment by alexcouper** [comment]
Great! Glad to hear it's providing value!

Whilst we haven't been actively developing new features, I'm hopeful that more time will be invested in this in the near future. We'd be very interested in hearing more about how you're using it in these projects and what features you'd like to see added.

**Comment by conradogarciaberrotaran** [comment]
Thank you for responding! Thanks for the great tool, it's sure providing value and an intuitive interface.

We're using it with [behave](https://behave.readthedocs.io/) by setting up several pretenders mock servers on the setup and asserting that requests are being done and also providing mock responses to those endpoints.
The most urgent feature requests I have right now is a new version that doesn't have insecure dependencies.
Right now, dependabot it's detecting `bottle`'s version as insecure.

I'd gladly create a PR to fix this if you're not available.

**Comment by conradogarciaberrotaran** [comment]
Hi! thanks @alexcouper for merging the [dependabot's PR](https://github.com/pretenders/pretenders/pull/142).
Is there any chance we can publish this as a new version to the pypi?

Thanks!

**Comment by alexcouper** [comment]
@conradogarciaberrotaran new version has been released! 1.4.5. Let me know if you have any issues with it.

**Comment by conradogarciaberrotaran** [comment]
Thanks! we're already up to date.
Keep up the good work!
